version: "3.8" # specify docker-compose version

# Define the services/containers to be run
services:
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
  
  rabitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#    - "2181:2181"
#    expose:
#    - "2181"    
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#    - "9092:9092"
#    expose:
#    - "9092"    
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

volumes:
  mongodata:

networks:
  backend: